---   
 <img align="left" width="75" height="75"  src="https://upload.wikimedia.org/wikipedia/en/c/c8/University_of_the_Punjab_logo.png"> 

<h1 align="center">Department of Data Science</h1>
<h1 align="center">Course: Tools and Techniques for Data Science</h1>

---
<h3><div align="right">Instructor: Muhammad Arif Butt, Ph.D.</div></h3>

<h1 align="center">Lecture 6.16 (Building a Machine Learning Pipeline (A-Z))</h1>

<a href="https://colab.research.google.com/github/arifpucit/data-science/blob/master/Section-4-Mathematics-for-Data-Science/Lec-4.1(Descriptive-Statistics).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <img align="center" width="900" src="images/ml-topimg1.png"  >

# Learning agenda of this notebook
<img align="right" width="580" src="images/pipeline-agenda1.png"  > 

- Data Preprocessing Techniques and Sklearn Transformers
    - Detecting and handling outliers
    - Missing values Imputation
    - Encoding Categorical Features
    - Feature Scaling
    - Extracting Information
    - Combining Information

- **Example 1:** Applying Transformers on Individual Columns
- **Example 2:** Use of sklearn's `ColumnTransformer` class


- <font face = "Garamond" color=green size=4>**Overview of Machine Learning Pipeline** </font>
    - What is a Machine Learning Pipeline?
    - Why to create a Machine Learning Pipeline?
    - How to create a Machine Learning Pipeline?


- **Example 3:** Use of sklearn's `Pipeline` Object
- **Example 4:** Use of sklearn's `Pipeline` Object(Advance)

# 1. Recap of Data Preprocessing Techniques and Scikit-Learn Transformers
Read Data Transformer in Scikit-Learn:https://scikit-learn.org/stable/data_transforms.html

- `Data Preprocessing` involves actions that we need to perform on the dataset in order to make it ready to be fed to the machine learning model.
- `Feature Engineering` is the process of using domain knowledge to extract features from raw data via data mining techniques.<br>
    
    <font face = "Garamond" color=green size=4>**a. Detecting and handling outliers** </font>

    <font face = "Garamond" color=green size=4>**b. Missing values Imputation** </font>

    <font face = "Garamond" color=green size=4>**c. Encoding Categorical Features**</font>
   
    <font face = "Garamond" color=green size=4>**d. Feature Scaling** </font>

    <font face = "Garamond" color=green size=4>**e. Extracting Information** </font>
    
    <font face = "Garamond" color=green size=4>**f. Combining Information** </font>
    
<br>
<img align="center" width="800" src="images/housing-dataset3.png"  >

## a. Missing Value Imputation
- **Why do we need to handle missing values?** 
    - If the missing values are not handled properly, you may end up building a biased machine learning model which will lead to incorrect results.
    - Many machine learning algorithms fail if the dataset contains missing values. However, algorithms like K-nearest and Naive Bayes support data with missing values.

- **How to treat missing values?**
    - Analyze each column with missing values carefully to understand the reasons behind the missing values as it is crucial to find out the strategy for handling the missing values. There are 2 primary ways of handling missing values:
        - Deleting the Missing values: Drop rows (List-wise deletion) having missing values or drop the entire column
        - Imputing the Missing Values: Replace the missing value with a value
            - `Univariate Imputation` 
                - Handling Missing Values using Panda's `fillna()` method
                - Handling Missing Values using sklearn's `SimpleImputer()` transformer
                - Use of Column Transformer
            - `Multivariate Imputation`
                - Handling Missing Values using sklearn's `IterativeImputer()` transformer 
                - Handling Missing Values using sklearn's `KNNImputer()` transformer  
<br><br>        
<img align="center" width="1000" src="images/imputer4.png"  >

## b. Encoding Categorical Features
    
<center><h4 align="center"><div class="alert alert-success" style="margin: 20px">Encoding categorical data is a process of converting it into numerical values, so that it could be fed to machine learning models</h4></center>

<img align="center" width="900" src="images/encoders1.png"  >

## c. Feature Scaling

<center><h3 align="center"><div class="alert alert-success" style="margin: 20px">Feature scaling is a process of transforming numeric columns to a common scale</h3></center> 
    
<img align="center" width="1000" src="images/scaling-how2.png"  >  
    
- **Normalization** is rescaling of the data from original range, so that all values are within the new range of 0 and 1.
- **Standardization** is rescaling of the data from original range, so that all values are centered around mean with a standard deviation of 1.
- `Note:` 
    - After scaling the distribution of data does not change.
    - Use standardization if your data is normally distributed, otherwise, use normalization
    - Standardization is more robust to outliers.

## d. Handling Outliers
<center><h3 align="center"><div class="alert alert-success" style="margin: 20px">An outlier is a data point that differs significantly from other observations</h3></center>

- **How to identify outliers?**
    - `Z Score Method:` $ x_i < \mu - 3\sigma \hspace{.5cm}\text{OR}\hspace{.5cm} x_i > \mu + 3\sigma $
    - `IQR Method`
    - `Percentiles Method`
    - Multivariate Analysis using Scatter Plot
    - There are a bundle of methods that you may come accross in literature like:
    - Depth-based methods
    - Distance-based methods
    - Density-based methods
    - Mahalanobis distance based methods


<img align="center" width="1000" src="images/outliers.png"  >

- **How to treat outliers?**
    - `Trimming`
    - `Capping/Winsorization`
    - `Discretization`

# 2. Practical Recap of Preprocessing using Scikit-Learn Transformers

## Example 1: Applying Transformers on Individual Columns

**Load Dataset**

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('datasets/salary-package1.csv')
df

    gender  cgpa      iq  salary
0     Male   2.3  Medium      68
1   Female   3.8    High     100
2     Male   3.0  Medium      75
3   Female   NaN     Low      48
4   Female   2.3    High      97
..     ...   ...     ...     ...
95  Female   2.1     Low      40
96  Female   2.3    High      68
97  Female   3.8    High     100
98  Female   3.0  Medium      75
99  Female   NaN    High      80

[100 rows x 4 columns]

In [2]:
#Check NaN values and datatypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   gender  100 non-null    object
 1   cgpa    90 non-null     float64
 2   iq      100 non-null    object
 3   salary  100 non-null    int64
dtypes: float64(1), int64(1), object(2)
memory usage: 3.2+ KB

In [3]:
df.isnull().sum()

gender     0
cgpa      10
iq         0
salary     0
dtype: int64

In [4]:
#Check unique values under object datatype columns
df.gender.unique()

array(['Male', 'Female'], dtype=object)

In [5]:
df.iq.unique()

array(['Medium', 'High', 'Low'], dtype=object)

**Train-Test Split**

In [6]:
from sklearn.model_selection import train_test_split
X = df.drop('salary', axis=1)
y = df['salary']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)
X_train.head()

   gender  cgpa      iq
0    Male   2.3  Medium
1  Female   3.8    High
2    Male   3.0  Medium
3  Female   NaN     Low
4  Female   2.3    High

**Apply `SimpleImputer` Transformer on `age` Column**

In [7]:
from sklearn.impute import SimpleImputer
# define imputer
si = SimpleImputer(missing_values=np.nan, strategy='mean')
#train it
si.fit(X_train[['cgpa']]) 

# transform() will return a numpy array which is being assigned to the cgpa column of dataframe
X_train['cgpa'] = si.transform(X_train[['cgpa']])
X_test['cgpa'] = si.transform(X_test[['cgpa']])
X_train.head()

   gender      cgpa      iq
0    Male  2.300000  Medium
1  Female  3.800000    High
2    Male  3.000000  Medium
3  Female  2.884507     Low
4  Female  2.300000    High

In [8]:
#Verify
X_train.isnull().sum()

gender    0
cgpa      0
iq        0
dtype: int64

**Apply `OneHotEncoder` Transformer on `gender` Column (Nominal Data)**

In [9]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first', sparse=False, dtype=np.int32)
#train
ohe.fit(X_train[['gender']])

# transform() will return a numpy array which is being assigned to the gender column of dataframe
X_train['gender'] = ohe.transform(X_train[['gender']])
X_test['gender'] = ohe.transform(X_test[['gender']])
#Verify
X_train.head()

   gender      cgpa      iq
0       1  2.300000  Medium
1       0  3.800000    High
2       1  3.000000  Medium
3       0  2.884507     Low
4       0  2.300000    High

**Apply `OrdinalEncoder` Transformer on `iq` Column (Ordinal Data)**

In [10]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Low', 'Medium', 'High']], dtype=np.int8)
#train
oe.fit(X_train[['iq']])
# transform() will return a numpy array which is being assigned to the gender column of dataframe
X_train['iq'] = oe.transform(X_train[['iq']])
X_test['iq'] = oe.transform(X_test[['iq']])
#verify
X_train.head()

   gender      cgpa  iq
0       1  2.300000   1
1       0  3.800000   2
2       1  3.000000   1
3       0  2.884507   0
4       0  2.300000   2

**Instentiate and Train `LinearRegression()` Model**

In [11]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train,y_train)

LinearRegression()

**Predict User Input**

In [12]:
test_input = np.array(['Male', 3.5, 'High']).reshape(1,3)
# Transform above user input to be fed to ML model 
test_input_transformed = np.array([1, 3.5, 2]).reshape(1,3)
test_input, test_input_transformed

(array([['Male', '3.5', 'High']], dtype='<U32'), array([[1. , 3.5, 2. ]]))

In [13]:
import warnings
warnings.filterwarnings('ignore')
model.predict(test_input_transformed)

array([73.12721804])

## Example 2: Repeat Example 1 using Scikit-Learn's `ColumnTransformer` Class
Visit ColumnTransformer Class in Scikit-Learn:https://scikit-learn.org/stable/modules/generated/sklearn.compose.ColumnTransformer.html

<h3 align="center"><div class="alert alert-success" color=magenta style="margin: 20px">ColumnTransformer allows to apply different Transformers on different columns of our dataset in a simple and elegant way</h3>

**Load Dataset**

In [57]:
import pandas as pd
import numpy as np
df = pd.read_csv('datasets/salary-package1.csv')
df

    gender  cgpa      iq  salary
0     Male   2.3  Medium      68
1   Female   3.8    High     100
2     Male   3.0  Medium      75
3   Female   NaN     Low      48
4   Female   2.3    High      97
..     ...   ...     ...     ...
95  Female   2.1     Low      40
96  Female   2.3    High      68
97  Female   3.8    High     100
98  Female   3.0  Medium      75
99  Female   NaN    High      80

[100 rows x 4 columns]

**Train-Test Split**

In [58]:
from sklearn.model_selection import train_test_split
X = df.drop('salary', axis=1)
y = df['salary']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

In [59]:
X_train

    gender  cgpa      iq
0     Male   2.3  Medium
1   Female   3.8    High
2     Male   3.0  Medium
3   Female   NaN     Low
4   Female   2.3    High
..     ...   ...     ...
75    Male   4.0     Low
76    Male   3.1     Low
77  Female   2.8  Medium
78    Male   2.5     Low
79  Female   3.1     Low

[80 rows x 3 columns]

**Create `ColumnTransformer` Object, Train and Transform**

In [60]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer

col_tfm = ColumnTransformer(
                        transformers=[
                                    ('tfm1', OneHotEncoder(drop='first',sparse=False),    ['gender']),
                                    ('tfm2', SimpleImputer(missing_values=np.nan, strategy='mean'),  ['cgpa']),
                                    ('tfm3', OrdinalEncoder(categories=[['Low', 'Medium', 'High']]), ['iq'])
                                     ],
                        remainder='passthrough')
type(col_tfm)

sklearn.compose._column_transformer.ColumnTransformer

In [61]:
# Train the ColumnTransformer object
col_tfm.fit(X_train)

ColumnTransformer(remainder='passthrough',
                  transformers=[('tfm1',
                                 OneHotEncoder(drop='first', sparse=False),
                                 ['gender']),
                                ('tfm2', SimpleImputer(), ['cgpa']),
                                ('tfm3',
                                 OrdinalEncoder(categories=[['Low', 'Medium',
                                                             'High']]),
                                 ['iq'])])

In [62]:
# Call transform on the trained ColumnTransformer object
# Return the transformed numPy array having three columns gender, cgpa, iq
arr_Xtrain = col_tfm.transform(X_train)
arr_Xtest = col_tfm.transform(X_test)
arr_Xtest

array([[0.        , 2.3       , 0.        ],
       [1.        , 3.8       , 0.        ],
       [1.        , 3.        , 1.        ],
       [0.        , 2.1       , 0.        ],
       [0.        , 2.3       , 2.        ],
       [0.        , 3.1       , 0.        ],
       [1.        , 2.4       , 0.        ],
       [1.        , 1.8       , 2.        ],
       [0.        , 1.1       , 0.        ],
       [1.        , 3.2       , 2.        ],
       [0.        , 3.6       , 1.        ],
       [1.        , 4.        , 0.        ],
       [0.        , 3.1       , 2.        ],
       [1.        , 2.8       , 0.        ],
       [1.        , 3.7       , 2.        ],
       [0.        , 2.1       , 0.        ],
       [0.        , 2.3       , 2.        ],
       [0.        , 3.8       , 2.        ],
       [0.        , 3.        , 1.        ],
       [0.        , 2.88450704, 2.        ]])

>- ColumnTransformer returns a numPy array even if we input a DataFrame object which makes it difficult to track the columns, i.e., we cannot track columns by name rather we have to track them by index.

**Instentiate and Train `LinearRegression()` Model**

In [20]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(arr_Xtrain, y_train)

LinearRegression()

**Predict**

In [21]:
test_input = np.array([['Male', 3.5, 'High']])
test_input_transformed = np.array([[1, 3.5, 2]])
test_input

array([['Male', '3.5', 'High']], dtype='<U32')

In [22]:
test_input = np.array(['Male', 3.5, 'High']).reshape(1,3)
test_input_transformed = np.array([1, 3.5, 2]).reshape(1,3)
test_input

array([['Male', '3.5', 'High']], dtype='<U32')

In [23]:
import warnings
warnings.filterwarnings('ignore')
model.predict(test_input_transformed)

array([73.12721804])

**Limitations of `ColumnTransformer`:**
- In a ColumnTransformer we cannot apply multiple transforms to a single column.
- ColumnTransformer returns a numPy array even if we input a DataFrame object which makes it difficult to track the columns, i.e., we cannot track columns by name rather we have to track them by index.

# 3. Overview of Machine Learning Pipeline

## What is a Machine Learning Pipeline?
<h3 align="center"><div class="alert alert-success" color=magenta style="margin: 20px">Pipeline is a mechanism that chains together multiple steps together so that the o/p of each step is used as i/p to the next step</h3>
    
<img align="center" width="1000" src="images/pipeline1.png"  > 
    
<h3 align="center"><div class="alert alert-success" color=magenta style="margin: 20px">A machine learning pipeline is simply a set of steps that you follow while working on your project. <br>This could include things like acquiring and preprocessing your data, training, hypertuning and validating models, and finally deploying them to make predictions. </h3>

>- The sequence of transformers does matter, as the output of each transformer become the input of next transformer
>- Moreover, there will be an estimator object at the end of the pipeline
>- Transformers can be built-in Scikit-Learn Transformer classes, or you can built your own customized transformers by inheriting that class from appropriate base transformer and base estimator classes.

## Why to Create a Machine Learning Pipeline?
<img align="center" width="800"  src="images/deployment.png"  >

## How to Create a Machine Learning Pipeline?
Visit Scikit-Learn Pipeline class documentation:https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html

## Example 3: Use of Scikit-Learn Pipeline Object

**Load Dataset**

In [24]:
import pandas as pd
import numpy as np
df = pd.read_csv('datasets/advertising-withmissingdata.csv')
df

        TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5    NaN       45.1   10.4
2      NaN   45.9       69.3    9.3
3    151.5   41.3        NaN   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    NaN        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0        NaN   25.5
199    NaN    8.6        8.7   13.4

[200 rows x 4 columns]

In [25]:
df.isnull().sum()

TV            4
radio        10
newspaper     2
sales         0
dtype: int64

<img align="center" width="600" src="images/pipeline2.png"  >

**Train-Test Split**

In [26]:
from sklearn.model_selection import train_test_split
X = df.drop('sales', axis=1)
y = df['sales']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=54)

**Create Pipeline Object, Train and Predict** <img align="center" width="600" src="images/pipeline2.png"  >

In [27]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

# steps argument of Pipeline() is a list of two valued tuples 
# unlike transformers argument of ColumnTransformer (3 valued tuple)
# SimpleImputer and StandardScaler will be applied to all the columns of the dataset
pipe = Pipeline(
               steps=[
                     ('si',  SimpleImputer(missing_values=np.nan, strategy='mean')),
                     ('ss',  StandardScaler()),
                     ('lr',  LinearRegression())
                    ]
                )
pipe

Pipeline(steps=[('si', SimpleImputer()), ('ss', StandardScaler()),
                ('lr', LinearRegression())])

In [28]:
# To graphically view what the pipeline object will do
from sklearn import set_config
set_config(display='diagram')
pipe

Pipeline(steps=[('si', SimpleImputer()), ('ss', StandardScaler()),
                ('lr', LinearRegression())])

**Train the Pipeline instead of Model**
- On a pipeline object, when you call the `fit()` method (by passing it raw or unprocessed training data), it will internally call the `fit_transform()` method of all transformers one after the other and transform the data. The transformed data is then passed to the final estimator which calls it's `fit()` method.

In [29]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('si', SimpleImputer()), ('ss', StandardScaler()),
                ('lr', LinearRegression())])

**Predict using the Pipeline instead of Model**
- On a trained pipeline object, when you call the `predict()` method (by passing raw or unprocessed test data), it will internally call only the `transform()` method of all transformers one after the other and transform the data.  The transformed test data is then passed to the final estimator which calls it's `predict()` method.

In [30]:
pipe.predict(X_test)

array([11.5103185 , 10.74314548, 17.06532765,  6.81320042,  9.7687584 ,
       11.81989768, 19.25928657, 10.56907364, 15.59736803, 16.11914409,
        9.73165545, 14.03714358, 16.43272133, 17.27575117,  8.87968169,
       23.35102195,  8.20884078, 13.29275029,  9.79142007, 11.38200247,
       18.68712032, 12.0133993 , 18.87632571, 20.56500684, 14.01595916,
       13.54109255, 18.17737359, 24.17518038,  9.15739432, 14.75927552,
       19.98104419,  9.76168882, 19.52101244, 21.27322187, 18.19830953,
       20.92010821,  6.60271388, 15.34461646, 20.26487212,  6.14806508])

**Evaluate using the Pipelined Model**

In [31]:
pipe.score(X_test, y_test)

0.850615741795994

In [32]:
# You can call methods on a specific transformer of this trained pipeline object
# Let us call fit_transform() on SimpleImputer, will return a NumPy array after imputing the missing values
pipe['si'].fit_transform(X_train)

array([[120.2       ,  19.6       ,  11.6       ],
       [145.63544304,  10.8       ,   6.        ],
       [210.7       ,  29.5       ,   9.3       ],
       [ 95.7       ,   1.4       ,   7.4       ],
       [276.9       ,  48.9       ,  41.8       ],
       [ 76.3       ,  27.5       ,  16.        ],
       [109.8       ,  14.3       ,  31.7       ],
       [121.        ,   8.4       ,  48.7       ],
       [ 75.1       ,  35.        ,  52.7       ],
       [ 94.2       ,  23.11      ,   8.1       ],
       [156.6       ,   2.6       ,   8.3       ],
       [109.8       ,  47.8       ,  51.4       ],
       [213.4       ,  23.11      ,  13.1       ],
       [ 70.6       ,  16.        ,  40.8       ],
       [283.6       ,  42.        ,  28.45886076],
       [261.3       ,  42.7       ,  54.7       ],
       [284.3       ,  10.6       ,   6.4       ],
       [104.6       ,   5.7       ,  34.4       ],
       [184.9       ,  43.9       ,   1.7       ],
       [ 25.6       ,  39.        ,   9.3       ],
       [170.2       ,   7.8       ,  35.2       ],
       [202.5       ,  22.3       ,  31.6       ],
       [100.4       ,   9.6       ,   3.6       ],
       [ 66.1       ,   5.8       ,  24.2       ],
       [228.        ,  37.7       ,  32.        ],
       [135.2       ,  41.7       ,  45.9       ],
       [ 18.7       ,  12.1       ,  23.4       ],
       [218.4       ,  27.7       ,  53.4       ],
       [234.5       ,   3.4       ,  84.8       ],
       [175.1       ,  22.5       ,  31.5       ],
       [188.4       ,  18.1       ,  25.6       ],
       [134.3       ,   4.9       ,   9.3       ],
       [ 19.6       ,  20.1       ,  17.        ],
       [164.5       ,  20.9       ,  47.4       ],
       [293.6       ,  27.7       ,   1.8       ],
       [ 62.3       ,  12.6       ,  18.3       ],
       [163.3       ,  31.6       ,  52.9       ],
       [280.7       ,  13.9       ,  37.        ],
       [123.1       ,  34.6       ,  12.4       ],
       [ 76.4       ,  26.7       ,  22.3       ],
       [129.4       ,   5.7       ,  31.3       ],
       [107.4       ,  14.        ,  10.9       ],
       [142.9       ,  29.3       ,  12.6       ],
       [ 76.4       ,   0.8       ,  14.8       ],
       [168.4       ,   7.1       ,  12.8       ],
       [  5.4       ,  29.9       ,   9.4       ],
       [175.7       ,  15.4       ,   2.4       ],
       [199.8       ,   3.1       ,  34.6       ],
       [110.7       ,  40.6       ,  63.2       ],
       [ 88.3       ,  25.5       ,  73.4       ],
       [193.2       ,  18.4       ,  65.7       ],
       [ 96.2       ,  14.8       ,  38.9       ],
       [ 80.2       ,   0.        ,   9.2       ],
       [120.5       ,  28.5       ,  14.2       ],
       [  8.7       ,  48.9       ,  75.        ],
       [199.1       ,  30.6       ,  38.7       ],
       [227.2       ,  15.8       ,  49.9       ],
       [266.9       ,  43.8       ,   5.        ],
       [217.7       ,  33.5       ,  59.        ],
       [182.6       ,  46.2       ,  58.7       ],
       [187.9       ,  17.2       ,  17.9       ],
       [ 31.5       ,  24.6       ,   2.2       ],
       [220.3       ,  49.        ,   3.2       ],
       [  8.4       ,  27.2       ,   2.1       ],
       [ 11.7       ,  36.9       ,  45.2       ],
       [ 97.2       ,   1.5       ,  30.        ],
       [ 13.2       ,  15.9       ,  49.6       ],
       [ 69.2       ,  20.5       ,  18.3       ],
       [ 43.1       ,  26.7       ,  35.1       ],
       [ 13.1       ,   0.4       ,  25.6       ],
       [289.7       ,  42.3       ,  51.2       ],
       [250.9       ,  23.11      ,  72.3       ],
       [210.8       ,  49.6       ,  37.7       ],
       [172.5       ,  18.1       ,  30.7       ],
       [ 18.8       ,  21.7       ,  50.4       ],
       [117.2       ,  14.7       ,   5.4       ],
       [184.9       ,  21.        ,  22.        ],
       [225.8       ,   8.2       ,  56.5       ],
       [209.6       ,  20.6       ,  10.7       ],
       [166.8       ,  42.        ,   3.6       ],
       [147.3       ,  23.11      ,  19.1       ],
       [102.7       ,  29.6       ,   8.4       ],
       [131.7       ,  18.4       ,  34.6       ],
       [ 39.5       ,  41.1       ,   5.8       ],
       [222.4       ,   4.3       ,  49.8       ],
       [215.4       ,  23.6       ,  57.6       ],
       [197.6       ,   3.5       ,   5.9       ],
       [224.        ,   2.4       ,  15.6       ],
       [ 74.7       ,  49.4       ,  45.7       ],
       [145.63544304,   8.6       ,   8.7       ],
       [222.4       ,   3.4       ,  13.1       ],
       [253.8       ,  21.3       ,  30.        ],
       [248.8       ,  27.1       ,  22.9       ],
       [213.5       ,  43.        ,  33.8       ],
       [ 69.        ,   9.3       ,   0.9       ],
       [116.        ,   7.7       ,  23.1       ],
       [ 50.        ,  11.6       ,  18.4       ],
       [ 28.6       ,   1.5       ,  33.        ],
       [237.4       ,  27.5       ,  11.        ],
       [163.5       ,  36.8       ,   7.4       ],
       [ 38.        ,  40.3       ,  11.9       ],
       [149.8       ,   1.3       ,  24.3       ],
       [205.        ,  45.1       ,  19.6       ],
       [237.4       ,   5.1       ,  23.5       ],
       [  7.8       ,  38.9       ,  50.6       ],
       [151.5       ,  41.3       ,  28.45886076],
       [ 89.7       ,  23.11      ,  35.7       ],
       [239.9       ,  41.5       ,  18.5       ],
       [  4.1       ,  11.6       ,   5.7       ],
       [177.        ,  33.4       ,  38.7       ],
       [290.7       ,  23.11      ,   8.5       ],
       [177.        ,   9.3       ,   6.4       ],
       [ 27.5       ,   1.6       ,  20.7       ],
       [240.1       ,  16.7       ,  22.9       ],
       [193.7       ,  35.4       ,  75.6       ],
       [ 73.4       ,  17.        ,  12.9       ],
       [255.4       ,  26.9       ,   5.5       ],
       [ 90.4       ,   0.3       ,  23.2       ],
       [ 59.6       ,  12.        ,  43.1       ],
       [243.2       ,  49.        ,  44.3       ],
       [ 26.8       ,  33.        ,  19.3       ],
       [219.8       ,  33.5       ,  45.1       ],
       [139.3       ,  14.5       ,  10.2       ],
       [204.1       ,  32.9       ,  46.        ],
       [ 68.4       ,  44.5       ,  35.6       ],
       [  8.6       ,   2.1       ,   1.        ],
       [240.1       ,   7.3       ,   8.7       ],
       [ 17.2       ,   4.1       ,  31.6       ],
       [206.8       ,   5.2       ,  19.4       ],
       [197.6       ,  23.11      ,  14.2       ],
       [187.8       ,  21.1       ,   9.5       ],
       [ 16.9       ,  43.7       ,  89.4       ],
       [136.2       ,  19.2       ,  16.6       ],
       [ 53.5       ,  23.11      ,  21.4       ],
       [262.7       ,  28.8       ,  15.9       ],
       [ 75.3       ,  20.3       ,  32.5       ],
       [ 44.5       ,  23.11      ,  45.1       ],
       [ 78.2       ,  23.11      ,  34.5       ],
       [265.2       ,   2.9       ,  43.        ],
       [ 38.2       ,   3.7       ,  13.8       ],
       [262.9       ,   3.5       ,  19.5       ],
       [141.3       ,  26.8       ,  46.2       ],
       [280.2       ,  10.1       ,  21.4       ],
       [ 67.8       ,  36.6       , 114.        ],
       [239.3       ,  15.5       ,  27.3       ],
       [292.9       ,  28.3       ,  43.2       ],
       [ 97.5       ,   7.6       ,   7.2       ],
       [216.4       ,  41.7       ,  39.6       ],
       [137.9       ,  46.4       ,  59.        ],
       [ 57.5       ,  32.8       ,  23.5       ],
       [199.8       ,   2.6       ,  21.2       ],
       [281.4       ,  39.6       ,  55.8       ],
       [ 48.3       ,  47.        ,   8.5       ],
       [  7.3       ,  28.1       ,  41.4       ],
       [131.1       ,  42.8       ,  28.9       ],
       [228.3       ,  16.9       ,  26.2       ],
       [195.4       ,  47.7       ,  52.9       ],
       [  0.7       ,  39.6       ,   8.7       ],
       [216.8       ,  43.9       ,  27.2       ],
       [241.7       ,  38.        ,  23.2       ]])

In [33]:
# You can call methods on a specific transformer of this trained pipeline object
# Let us call fit_transform() on StandardScalar, will return a NumPy array after scaling the data
pipe['ss'].fit_transform(X_train)

array([[-0.30146403, -0.2337849 , -0.82091279],
       [        nan, -0.81991227, -1.09359501],
       [ 0.7711532 ,  0.4256084 , -0.93290727],
       [-0.59184107, -1.44600287, -1.02542445],
       [ 1.55576382,  1.71775284,  0.64962348],
       [-0.82177228,  0.29239763, -0.60666247],
       [-0.42472612, -0.58679343,  0.15782162],
       [-0.29198233, -0.97976519,  0.98560693],
       [-0.83599483,  0.79193801,  1.18037995],
       [-0.60961925,         nan, -0.99133917],
       [ 0.12995329, -1.36607641, -0.98160052],
       [-0.42472612,  1.64448692,  1.11707872],
       [ 0.80315394,         nan, -0.74787291],
       [-0.88932938, -0.47356428,  0.60093023],
       [ 1.63517305,  1.25817569,         nan],
       [ 1.37087068,  1.30479946,  1.27776645],
       [ 1.64346954, -0.83323335, -1.07411771],
       [-0.48635716, -1.15959972,  0.2892934 ],
       [ 0.4653684 ,  1.38472592, -1.302976  ],
       [-1.42267497,  1.05835954, -0.93290727],
       [ 0.29114218, -1.01972842,  0.328248  ],
       [ 0.67396579, -0.05395036,  0.15295229],
       [-0.53613609, -0.89983873, -1.21045882],
       [-0.94266394, -1.15293919, -0.20737779],
       [ 0.97619495,  0.97177254,  0.17242959],
       [-0.12368217,  1.23819408,  0.84926582],
       [-1.50445463, -0.73332527, -0.24633239],
       [ 0.86241456,  0.30571871,  1.21446522],
       [ 1.05323376, -1.31279211,  2.74343339],
       [ 0.34921759, -0.04062928,  0.14808296],
       [ 0.50685084, -0.33369297, -0.13920723],
       [-0.13434908, -1.21288403, -0.93290727],
       [-1.49378771, -0.2004822 , -0.55796922],
       [ 0.22358507, -0.1471979 ,  0.9223057 ],
       [ 1.75369429,  0.30571871, -1.29810667],
       [-0.98770201, -0.70002258, -0.49466799],
       [ 0.20936252,  0.5654797 ,  1.1901186 ],
       [ 1.60080189, -0.61343558,  0.41589586],
       [-0.26709287,  0.76529585, -0.78195818],
       [-0.82058706,  0.23911333, -0.29989497],
       [-0.19242449, -1.15959972,  0.13834431],
       [-0.45317122, -0.60677504, -0.85499806],
       [-0.03242081,  0.41228732, -0.77221953],
       [-0.82058706, -1.4859661 , -0.66509437],
       [ 0.26980835, -1.06635219, -0.76248088],
       [-1.66208788,  0.45225055, -0.92803794],
       [ 0.35632886, -0.51352751, -1.26889072],
       [ 0.64196505, -1.33277372,  0.29903205],
       [-0.41405921,  1.16492816,  1.69165911],
       [-0.67954679,  0.15918687,  2.1883303 ],
       [ 0.56374103, -0.31371136,  1.81339225],
       [-0.58591501, -0.55349074,  0.50841304],
       [-0.77554899, -1.53925041, -0.9377766 ],
       [-0.29790839,  0.35900302, -0.69431033],
       [-1.62297587,  1.71775284,  2.26623951],
       [ 0.63366856,  0.49887432,  0.49867439],
       [ 0.96671325, -0.48688535,  1.04403884],
       [ 1.43724258,  1.37806538, -1.14228826],
       [ 0.85411807,  0.69202993,  1.48714744],
       [ 0.43810852,  1.5379183 ,  1.47253947],
       [ 0.50092477, -0.39363782, -0.51414529],
       [-1.35274744,  0.09924202, -1.27862937],
       [ 0.8849336 ,  1.72441338, -1.22993612],
       [-1.6265315 ,  0.27241602, -1.2834987 ],
       [-1.58741949,  0.91848824,  0.81518054],
       [-0.57406288, -1.43934233,  0.07504308],
       [-1.56964131, -0.48022481,  1.02943086],
       [-0.90592236, -0.17384005, -0.49466799],
       [-1.2152628 ,  0.23911333,  0.32337868],
       [-1.57082652, -1.51260826, -0.13920723],
       [ 1.70747101,  1.27815731,  1.10734007],
       [ 1.24760859,         nan,  2.13476772],
       [ 0.77233842,  1.76437661,  0.44998114],
       [ 0.31840206, -0.33369297,  0.10912836],
       [-1.50326941, -0.09391359,  1.06838546],
       [-0.3370204 , -0.56015127, -1.12281096],
       [ 0.4653684 , -0.14053736, -0.31450295],
       [ 0.95012028, -0.99308627,  1.36541431],
       [ 0.75811587, -0.16717951, -0.86473671],
       [ 0.25084496,  1.25817569, -1.21045882],
       [ 0.01972854,         nan, -0.45571338],
       [-0.5088762 ,  0.43226894, -0.9767312 ],
       [-0.1651646 , -0.31371136,  0.29903205],
       [-1.25793044,  1.19823085, -1.10333366],
       [ 0.90982306, -1.25284726,  1.03916951],
       [ 0.82685819,  0.03263664,  1.41897689],
       [ 0.61589038, -1.30613157, -1.09846433],
       [ 0.92878646, -1.37939749, -0.62613977],
       [-0.84073567,  1.75105553,  0.83952717],
       [        nan, -0.96644411, -0.96212322],
       [ 0.90982306, -1.31279211, -0.74787291],
       [ 1.28197975, -0.12055574,  0.07504308],
       [ 1.22271913,  0.26575548, -0.27067902],
       [ 0.80433915,  1.32478108,  0.26007745],
       [-0.90829278, -0.91982034, -1.3419306 ],
       [-0.35124295, -1.02638896, -0.26094037],
       [-1.13348314, -0.76662796, -0.48979866],
       [-1.3871186 , -1.43934233,  0.22112285],
       [ 1.08760492,  0.29239763, -0.85012874],
       [ 0.21173295,  0.9118277 , -1.02542445],
       [-1.27570863,  1.14494654, -0.80630481],
       [ 0.04935885, -1.45266341, -0.20250846],
       [ 0.7035961 ,  1.46465238, -0.43136676],
       [ 1.08760492, -1.19956295, -0.24146307],
       [-1.63364278,  1.051699  ,  1.07812411],
       [ 0.06950746,  1.21155192,         nan],
       [-0.66295381,         nan,  0.35259463],
       [ 1.11723523,  1.224873  , -0.48492933],
       [-1.67749564, -0.76662796, -1.10820298],
       [ 0.37173662,  0.68536939,  0.49867439],
       [ 1.71932313,         nan, -0.97186187],
       [ 0.37173662, -0.91982034, -1.07411771],
       [-1.40015593, -1.4326818 , -0.37780418],
       [ 1.11960565, -0.42694051, -0.27067902],
       [ 0.56966709,  0.81858016,  2.29545546],
       [-0.85614344, -0.40695889, -0.75761156],
       [ 1.30094315,  0.2524344 , -1.11794163],
       [-0.65465733, -1.51926879, -0.25607104],
       [-1.01970275, -0.73998581,  0.71292471],
       [ 1.15634724,  1.72441338,  0.77135661],
       [-1.40845242,  0.65872724, -0.44597473],
       [ 0.87900753,  0.69202993,  0.81031122],
       [-0.07508846, -0.57347235, -0.88908334],
       [ 0.69292919,  0.6520667 ,  0.85413515],
       [-0.91540406,  1.42468915,  0.34772531],
       [-1.62416108, -1.3993791 , -1.33706128],
       [ 1.11960565, -1.05303111, -0.96212322],
       [-1.52223281, -1.26616834,  0.15295229],
       [ 0.72492992, -1.19290242, -0.44110541],
       [ 0.61589038,         nan, -0.69431033],
       [ 0.49973956, -0.13387682, -0.92316862],
       [-1.52578845,  1.37140484,  2.96742236],
       [-0.11183004, -0.26042705, -0.57744652],
       [-1.09200071,         nan, -0.3437189 ],
       [ 1.38746366,  0.37898463, -0.61153179],
       [-0.8336244 , -0.18716113,  0.19677622],
       [-1.19866982,         nan,  0.81031122],
       [-0.79925324,         nan,  0.29416273],
       [ 1.41709397, -1.3460948 ,  0.70805538],
       [-1.27333821, -1.29281049, -0.71378763],
       [ 1.38983408, -1.30613157, -0.43623608],
       [-0.05138421,  0.24577386,  0.8638738 ],
       [ 1.59487583, -0.86653604, -0.3437189 ],
       [-0.92251533,  0.89850662,  4.1652764 ],
       [ 1.11012395, -0.50686697, -0.0564287 ],
       [ 1.74539781,  0.34568194,  0.71779403],
       [-0.57050725, -1.0330495 , -1.0351631 ],
       [ 0.83871031,  1.23819408,  0.54249832],
       [-0.09168143,  1.55123938,  1.48714744],
       [-1.04459221,  0.64540616, -0.24146307],
       [ 0.64196505, -1.36607641, -0.35345755],
       [ 1.60909838,  1.09832277,  1.33132903],
       [-1.15363175,  1.59120261, -0.97186187],
       [-1.63956884,  0.33236086,  0.63014618],
       [-0.17227587,  1.31146   ,  0.02148051],
       [ 0.97975059, -0.41361943, -0.10999128],
       [ 0.58981571,  1.63782638,  1.1901186 ],
       [-1.71779286,  1.09832277, -0.96212322],
       [ 0.84345116,  1.38472592, -0.06129803],
       [ 1.13856905,  0.99175416, -0.25607104]])

In [34]:
# Let us call fit() on estimator, will raise an error because X_train contains NaN values
#pipe['lr'].fit(X_train, y_train)

**Predict**

In [35]:
TV = 60
radio = np.nan
newspaper = 40
test_input = np.array([[TV, radio, newspaper]])
test_input = np.array([TV, radio, newspaper]).reshape(1,3)
test_input

array([[60., nan, 40.]])

In [36]:
pipe.predict(test_input)

array([10.0297736])

## Example 4: Using ColumnTransformer in a Pipeline

- A transformer in a pipeline is applied on the entire input dataset or the o/p of the previous transformer. 
- We can have missing values in numeric variables as well as missing values in categorical variables, so we have to use different imputation techniques on numeric columns and different techniques on categorical columns.
- Moreover we have to apply different encoding techniques to categorical columns, for nominal data we apply OneHotEncoder while for ordinal data we apply OrdinalEncoder
- At times we want to apply different transformation to different columns of our dataset. For this we can create multiple pipelines and later combine them together
    - For processing numeric data we can create a separate pipeline
    - For processing categorical data we can create a separate pipeline
    - Later we can combine these two pipelines to a single one, and later any transformer that we place in the pipeline will be applied to the entire output dataset of the previous step of pipeline :)

### Load Dataset

In [37]:
import numpy as np
import pandas as pd
import seaborn as sns

#df = sns.load_dataset('tips')
df = pd.read_csv('datasets/tips-missingdata.csv')
df.head()

   total_bill     sex smoker  day    time  size   tip
0       16.99  Female     No  Sun  Dinner     2   NaN
1         NaN    Male    NaN  Sun  Dinner     3  1.66
2       21.01    Male     No  Sun  Dinner     3  3.50
3       23.68     NaN     No  Sun  Dinner     2  3.31
4       24.59  Female     No  Sun  Dinner     4  3.61

In [38]:
df.dtypes

total_bill    float64
sex            object
smoker         object
day            object
time           object
size            int64
tip           float64
dtype: object

In [39]:
df.day.unique()

array(['Sun', 'Sat', 'Thur', 'Fri'], dtype=object)

In [40]:
df.isna().sum()

total_bill    3
sex           2
smoker        1
day           0
time          0
size          0
tip           1
dtype: int64

**Drop rows where o/p label `tip` has missing values**

In [41]:
df.dropna(axis=0, how='any', subset=['tip'], inplace=True)
df.isna().sum()

total_bill    3
sex           2
smoker        1
day           0
time          0
size          0
tip           0
dtype: int64

In [42]:
df.shape

(243, 7)

### Train-Test Split

In [43]:
from sklearn.model_selection import train_test_split
X = df.drop('tip', axis=1)
y = df['tip']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=54)

> If we impute missing values under `total_bill` column before splitting it into train and test with the `mean()` of the whole column values. Then, this would result in  information leakage, i.e., using information from the test set to fill the training set.

## Design of Pipeline

In [44]:
X_train

     total_bill     sex smoker   day    time  size
35        24.06    Male     No   Sat  Dinner     3
56        38.01    Male    Yes   Sat  Dinner     4
6          8.77    Male     No   Sun  Dinner     2
34        17.78    Male     No   Sat  Dinner     2
107       25.21    Male    Yes   Sat  Dinner     2
..          ...     ...    ...   ...     ...   ...
24        19.82    Male     No   Sat  Dinner     2
16        10.33  Female     No   Sun  Dinner     3
131       20.27  Female     No  Thur   Lunch     2
70        12.02    Male     No   Sat  Dinner     2
112       38.07    Male     No   Sun  Dinner     3

[194 rows x 6 columns]

<img align="center" width="600" src="images/pipe-gr8.png"  >

### Create Pipeline Object, Train and Predict

**Create Two Pipeline Objects to handle Categorical and Numeric Data**

In [45]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer 
from sklearn.preprocessing import OneHotEncoder

# Preprocess categorical columns ("sex", "smoker", "day", "time")
categorical_transformer = Pipeline(steps=[
                                     ('imputer', SimpleImputer(missing_values=np.nan, strategy='most_frequent')),
                                     ('onehot', OneHotEncoder(drop='first', handle_unknown='ignore'))
                                   ])

# Preprocess numeric columns ("total_bill", "size")
numeric_transformer = Pipeline(steps=[
                                      ('imputer', SimpleImputer(missing_values=np.nan, strategy='mean'))  
                                  ])

**Combine above two Pipelines using ColumnTransformer**

In [46]:
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer(
                              transformers=[
                                           ('categorical', categorical_transformer, [1,2,3,4]),
                                           ('numerical', numeric_transformer, [0,5])
                                           ]
                                )

**Create the Final Pipeline Object**

In [47]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

model = Pipeline(steps=[
                        ('preprocessor', preprocessor),
                        ('scaling', StandardScaler()),
                        ('regressor', LinearRegression())
                       ])

model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore'))]),
                                                  [1, 2, 3, 4]),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer())]),
                                                  [0, 5])])),
                ('scaling', StandardScaler()),
                ('regressor', LinearRegression())])

In [48]:
X_train

     total_bill     sex smoker   day    time  size
35        24.06    Male     No   Sat  Dinner     3
56        38.01    Male    Yes   Sat  Dinner     4
6          8.77    Male     No   Sun  Dinner     2
34        17.78    Male     No   Sat  Dinner     2
107       25.21    Male    Yes   Sat  Dinner     2
..          ...     ...    ...   ...     ...   ...
24        19.82    Male     No   Sat  Dinner     2
16        10.33  Female     No   Sun  Dinner     3
131       20.27  Female     No  Thur   Lunch     2
70        12.02    Male     No   Sat  Dinner     2
112       38.07    Male     No   Sun  Dinner     3

[194 rows x 6 columns]

**Train and Evaluate the Pipeline Object**

In [12]:
# Note: when fit() is called on a Pipeline object, internally 
# it will call the fit_transform() method on all the transformers and fit() on the estimator

model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore'))]),
                                                  [1, 2, 3, 4]),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer())]),
                                                  [0, 5])])),
                ('scaling', StandardScaler()),
                ('regressor', LinearRegression())])

In [13]:
# Note: when score() or predict() is called on a Pipeline object, internally 
# only the transform() method is called on all the transformers and score() / predict() on the estimator
model.score(X_test, y_test)

0.3919649062043292

**Predict on new input**

In [51]:
total_bill = 100
sex = 'Male'
smoker = 'Yes'
day = 'Sun'
time = 'Dinner'
size = 4
test_input = np.array([[total_bill, sex, smoker, day, time, size]], dtype='object')
test_input

array([[100, 'Male', 'Yes', 'Sun', 'Dinner', 4]], dtype=object)

In [52]:
test_input.shape

(1, 6)

In [53]:
# This will not work if you give string names of columns while creating the column transformer
model.predict(test_input)

array([10.34508622])

### Cross Validation using Pipeline
Okay, knowing all this, let's cross-validate our model pipeline using [cross_val_score()](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html)

In [54]:
from sklearn.model_selection import cross_val_score
cross_val_score(model, 
                X_train, 
                y_train, 
                cv=5, 
                scoring='r2')

array([0.33120287, 0.3581081 , 0.57774671, 0.32420228, 0.47500525])

In [55]:
cross_val_score(model, X_train, y_train, cv=5, scoring='r2').mean()

0.4132530407042142

### Putting all the Code in one Cell

In [56]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
import warnings
warnings.filterwarnings('ignore')

# Read the data
df = pd.read_csv('datasets/tips-missingdata.csv')
# Drop the rows with no labels
df.dropna(axis=0, how='any', subset=['tip'], inplace=True)
# Split data into X (data) & y (labels) and do a train-test split
X = df.drop('tip', axis=1)
y = df['tip']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=54)
X_train


# Preprocess categorical columns ("sex", "smoker", "day", "time")
categorical_transformer = Pipeline(steps=[
                                     ('imputer', SimpleImputer(missing_values=np.nan, strategy='most_frequent')),
                                     ('onehot', OneHotEncoder(drop='first', handle_unknown='ignore'))
                                   ])
# Preprocess numeric columns ("total_bill", "size")
numeric_transformer = Pipeline(steps=[
                                      ('imputer', SimpleImputer(missing_values=np.nan, strategy='mean'))  
                                  ])
# Create a column transformer which combines all of the other transformers into one step
preprocessor = ColumnTransformer(
                              transformers=[
                                           ('categorical', categorical_transformer, [1,2,3,4]),
                                           ('numerical', numeric_transformer, [0,5])
                                           ]
                               )         
# Create the final pipeline
model = Pipeline(steps=[('preprocessor', preprocessor),
                        ('scaling', StandardScaler()),
                        ('regressor', LinearRegression())])

# Fit the model on the training data 
model.fit(X_train, y_train)

print("R2 Score:", cross_val_score(model,X_train, y_train, cv=5, scoring='r2').mean())
test_input = np.array([[100, 'Male', 'Yes', 'Sun', 'Dinner', 4]], dtype='object')
print("Predicted tip amount: ", model.predict(test_input))

R2 Score: 0.4132530407042142
Predicted tip amount:  [10.34508622]

# Task To Do
I'd suggest the following reading resources and next steps before doing the task.
* **Reading:** [Scikit-Learn Pipeline() documentation](https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html).
* **Reading:** [Imputing missing values before building an estimator](https://scikit-learn.org/stable/auto_examples/impute/plot_missing_values.html) (compares different methods of imputing values).
* **Practice:** Try [tuning model hyperparameters with a `Pipeline()` and `GridSearchCV()`](https://scikit-learn.org/stable/modules/grid_search.html#composite-estimators-and-parameter-spaces).

In [57]:
import pandas as pd
import numpy as np
df = pd.read_csv('datasets/big_mart_sales.csv')
df

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

**Sales Prediction for Big Mart Outlets**
- The data scientists at BigMart have collected 2013 sales data for 1559 products across 10 stores in different cities. Also, certain attributes of each product and store have been defined. The aim is to build a predictive model and predict the sales of each product at a particular outlet.

- Using this model, BigMart will try to understand the properties of products and outlets which play a key role in increasing sales.

- Please note that the data may have missing values as some stores might not report all the data due to technical glitches. Hence, it will be required to treat them accordingly.

<img align="center" width="800" src="images/bigmartdata-description.png"  >